### ISSUE TITLE
[CONF] Pin changes and additions for M2.0 / AON-M2

### ISSUE THREAD

**Issue by Rooaboo** [aon3d/m1-firmware#3]
Open new branch, make following changes:
1) Remove bed leveling from Ymax
2) Set Ymax to parallel Y Endstop
3) Add two I/O pins for individual toolhead mechanical probe ( micro switch: normally open) bed leveling
4) Investigate appropriate pins for filament sensing ( confirm if one or two units )
5) Add pins for filament sensing

**Comment by mdtusz** [comment]
@caenan0 @peteroon any additional insight for this one regarding the probe, filament sensors etc? I've been out of the firmware/hardware side of things for a while but can jump back in sometime this week.

**Comment by nivekhan** [comment]
Given that every endstop pin is now actually used for an endstop, this means we need additional pins for the following: 

-Bed probe needs a Signal and a Gnd x 2
-PT100 amplifiers require a 5V, Gnd, and Signal x 2
-Filament sensors require 5V, Gnd, Signal, but can be daisy chained so only requires 1 set. (ref https://dyzedesign.com/support/filament-sentinel-technical-support)

Total signal pins req'd = 5
Total 5V/Gnd pairs req'd = 3
Total Gnd req'd = 2

Referencing the azteeg wiring diagram (http://files.panucatt.com/datasheets/x3pro_wiring.pdf) we have more than enough signal pins (Unused D## on the EXP3 header) for our purposes. We do not have enough 5V/Gnd pairs however so we'll need to either splice wires or create another small breakout board. 

The PT100's must be connected to A9/D63 and A3/D57 however as they need the ADC (analog-to-digital) conversion.

Pins 35/32/31 are currently used as a "dummy stepper" for a "third hot end" (ie. the chamber), so assigning probes/sensors to that will wreak unknown havoc if the user accidentally sends a travel move while T2/Chamber is activated. 

44 is assigned to "case lighting" which isn't actually used right now but may be good to reserve it for the future. 

47 is assigned to a servo which is an unused feature but the servo object is related to a lot of bed leveling stuff so undefining it probably will cause compile errors. 

By my account that leaves D39, D45, D12, and D49 available for use. My recommendation would be to use D49 for filament sensing as it's right next to the 5V and Gnd pins. D45 has PWM which might be useful for something else in the future, so D39 and D12 for probe signal would be ideal. 

Lmk if there are problems reassigning the rest but @mdtusz and @Rooaboo can probs figure it out
